version = '0.5.1'  # REDUNDANT: MAKE SURE THIS MATCHES THE VERSION setup.py
version_notes = ('Scheduler-aware submit-kwarg translation on top of the 0.5.0 '
                 'transport seam (t_8c583eba / CDM card: "harness sends '
                 'Slurm-only --mem/--nice to the LSF submit script"). Generic '
                 'submit kwargs (mem, nice, ...) are translated by the '
                 'scheduler backend before they are forwarded to the submit '
                 'script, ahead of transport.exec_argv in both '
                 'HPCSession.submit and HPCSession.resubmit_job (works through '
                 'SSHTransport and LocalTransport alike): LSFBackend turns '
                 'mem (Slurm syntax, e.g. 32G) into mem_mb (integer MB; '
                 'hpc_scripts/lsf.py renders it as rusage[mem=<MB>] inside '
                 'the single -R, per the no-multiple-R rule verified on '
                 'sjlsf01) and drops nice (no bsub equivalent; logged at '
                 'debug). SlurmBackend stays byte-identical (identity '
                 'passthrough, pinned by a unit test). No scheduler-specific '
                 'values in any caller -- the same generic kwargs work on '
                 'Windows+Slurm, Windows+LSF and Linux+LSF purely via '
                 '~/.aview_hpc -- and lsf.py unknown-argument guard unchanged '
                 'for genuinely unsupported options. Fixes CDM CI run '
                 '37824964058 (set 1 a, use_hpc=true: "Unsupported arguments '
                 'forwarded to bsub ... --mem 32G --nice 2147483645").')
date = 'October, 9th 2026'
