version = '0.5.4'  # REDUNDANT: MAKE SURE THIS MATCHES THE VERSION setup.py
version_notes = ('LSF PEND jobs get a WorkDir from sub_cwd (t_96514c3c / '
                 'CDM card: "HPC: LSF PEND jobs read as \'absent\' (bjobs '
                 'EXEC_CWD empty until dispatch) and get killed after '
                 '900 s"). LSFBackend.JOB_TABLE_FIELDS gains sub_cwd and '
                 'WorkDir = EXEC_CWD, falling back to SUB_CWD when EXEC_CWD '
                 'is empty. LSF leaves EXEC_CWD empty until a job is '
                 'dispatched to a host, so a PEND row previously carried '
                 'WorkDir \'\' -- invisible to WorkDir-keyed consumers '
                 '(CDM\'s scheduler_state / wait_for_hpc_jobs match rows by '
                 'WorkDir == remote_dir), which read a queued job as '
                 '"absent" and killed it after the 900 s '
                 'ABSENT_FROM_TABLE_GRACE_S (CI run 37939750883 set 83: '
                 'two sub-sims "presumed lost" while they sat ~18 min in '
                 'PEND and later completed fine). SUB_CWD is fixed at '
                 'submission and equals the submission cwd, which for '
                 'aview_hpc submissions IS the remote dir '
                 '(hpc_scripts/lsf.py chdirs to the acf\'s dir before '
                 'bsub). Live-verified on sjlsf01 2026-10-09: RUN '
                 'aview_hpc jobs report SUB_CWD == EXEC_CWD == the remote '
                 'dir, and a job HELD in the queue (bsub -H, submitted '
                 'with cwd = remote dir) reports SUB_CWD = the exact '
                 'absolute remote-dir string with EXEC_CWD \'\' (STAT '
                 'PSUSP). Only an ABSOLUTE SUB_CWD is used: LSF reports '
                 'the literal \'$HOME\' or \'$HOME/...\' when the '
                 'submission cwd is home-based or not representable '
                 '(live-observed: \'$HOME/hpc_tmp/test.XXX\' vs the '
                 'expanded EXEC_CWD /home/thornton/hpc_tmp/test.XXX), and '
                 'those degrade to \'\' -- the pre-0.5.4 behavior -- '
                 'instead of becoming a bogus WorkDir. CDM-side, PR #740\'s '
                 'PENDING state mapping already treats a found PEND row as '
                 'ACTIVE, and the harness additionally matches by JobId '
                 'when it has one (aview_hpc has always returned job ids '
                 'from submit_multi/resubmit_job). The slurm backend is '
                 'unchanged (its sacct command is frozen byte-for-byte, '
                 'pinned by test).')
date = 'October, 9th 2026'
