version = '0.5.2'  # REDUNDANT: MAKE SURE THIS MATCHES THE VERSION setup.py
version_notes = ('Hermetic in-process CLI capture (t_11595f7b / CDM card: '
                 '"LSF job runs DONE but submit_multi json.loads(out) fails '
                 'under in-process + LocalTransport"). The 0.5.1 stream-swap '
                 'only re-pointed root logging handlers that HAVE a .stream '
                 'attribute; host handlers whose emit() writes via print() '
                 'bypassed it -- inside Adams View the CDM plugin installs '
                 'exactly such a handler (AdamsLogFileHandler, general/'
                 'log.py), and under redirect_stdout its records landed in '
                 'the JSON capture buffer ahead of the payload: CI run '
                 '37923731507 submitted LSF job 1337242 (DONE, clean '
                 'stderr) and died at json.loads(out) char 0. '
                 '_run_cli_inprocess now DETACHES every existing root '
                 'handler for the duration of the CLI call (restored in '
                 'order in finally) and collects all logging in a scratch '
                 'buffer, so the CLI stdout is ONLY the CLI payload '
                 'regardless of handler type. Layer 2: aview_hpc.py parses '
                 'the CLI stdout defensively (_parse_cli_json) -- whole '
                 'buffer, then last JSON-object line, then a RuntimeError '
                 '(which the CDM harness retries) instead of a bare '
                 'JSONDecodeError (which it does not catch). Fixes set 1 '
                 'use_hpc dying ~1 min into CI run 37923731507.')
date = 'October, 9th 2026'
