#! /usr/bin/python3
'''Submit an ACF file to the cluster using LSF (Cadence sjlsf01 farm)

usage: lsf.py <acf_file> [options]

positional arguments:
  acf_file              Path to the ACF file

optional arguments:
  -h, --help            show this help message and exit
  --mins MINS           Wall-clock limit for the job, in minutes (default: 720)
  --queue QUEUE         LSF queue (default: lnx64)
  --project PROJECT     Charge code, format PRODUCT:RELEASE:GROUP:PURPOSE
                        (required; can also be supplied via $LSF_PROJECT)
  --res_req RES_REQ     LSF resource requirement string (default: pins to
                        RHEL 8.6+ or RHEL 9 hosts)
  --adams_home DIR      Adams installation directory containing `mdi`
                        (required; can also be supplied via $ADAMS_HOME)
  --license LICENSE     MSC license file string, e.g. 1700@sjflex5
                        (required; can also be supplied via $MSC_LICENSE_FILE)
  --ld_library_path P   Optional LD_LIBRARY_PATH for the solver
                        (can also be supplied via $ADAMS_LD_LIBRARY_PATH)
  --email EMAIL         bsub -u value (default: noemail)
  --dry_run             Print the bsub command line and the job script
                        instead of submitting

note:
  This will recognize the following:
    * The .adm file from the .acf file
    * The NTHREADS option in the .adm file

The submission goes through the site wrapper /grid/sfi/farm/bin/bsub, which
enforces the Cadence farm rules (mandatory -W and -P, etc.). On success bsub
prints "Job <id> is submitted to queue <queue>.", which is what the
aview_hpc client parses.
'''

import argparse
import os
import re
import shlex
import subprocess
import sys
import traceback as tb
from contextlib import contextmanager
from pathlib import Path

BSUB = '/grid/sfi/farm/bin/bsub'
DEFAULT_QUEUE = 'lnx64'
DEFAULT_RES_REQ = 'select[(OSMJR==8 && OSMNR>=6) || OSMJR>=9]'
RE_PROJECT = re.compile(r'[A-Z]+:[^:]+:[A-Z]+:[^:]+')

RE_MODEL = re.compile(r'file/.*model[ \t]*=[ \t]*(.+)[ \t]*(?:,|$)', flags=re.I | re.MULTILINE)
RE_NTHREADS = re.compile(r'nthreads[ \t]*=[ \t]*(\d+)\b', flags=re.I)

JOB_SCRIPT_TEMPLATE = '''#!/bin/sh
# LSF job script generated by aview_hpc hpc_scripts/lsf.py
export LC_ALL=C
export MSC_LICENSE_FILE={license_file}
{ld_library_path}{adams_home}/mdi -c ru-s i {acf_file} exit
'''


def get_adm_from_acf(acf_file: Path):
    text = acf_file.read_text()

    try:
        line = next(l for l in text.splitlines())
    except StopIteration:
        raise ValueError(f'{acf_file} has no contents!')

    if line.strip() != '':
        file = line.strip()

    else:

        try:
            file = next(m for m in RE_MODEL.findall(text))
        except StopIteration:
            raise ValueError(f'No model name was found in {acf_file}')

    adm_file = Path(file)
    if not adm_file.suffix:
        adm_file = adm_file.with_suffix('.adm')

    return acf_file.parent / adm_file


def get_n_cpus(adm_file: Path):
    text = adm_file.read_text()
    try:
        n_threads = int(next(m for m in RE_NTHREADS.findall(text)))
    except StopIteration:
        # Set n_threads to 1 if not specified in .adm file
        n_threads = 1

    return n_threads


def get_unique_file_name(filename: Path):
    new_name = filename
    for i in range(999):

        if not new_name.exists():
            break

        new_name = filename.parent / f'{filename.stem}_{i}{filename.suffix}'

    return new_name


def format_wallclock(mins: int) -> str:
    """Format minutes as bsub's ``[hours:]minutes`` wall-clock limit."""
    mins = int(mins)
    if mins <= 0:
        raise ValueError('--mins must be a positive integer')
    return f'{mins // 60}:{mins % 60:02d}'


def build_job_script(acf_file: Path, license_file: str, adams_home: str,
                     ld_library_path: str = None) -> str:
    """Build the LSF job script contents."""
    return JOB_SCRIPT_TEMPLATE.format(
        license_file=license_file,
        ld_library_path=(f'export LD_LIBRARY_PATH={ld_library_path}\n'
                         if ld_library_path else ''),
        adams_home=str(adams_home).rstrip('/'),
        acf_file=Path(acf_file).name)


def build_bsub_command(script_file, job_name: str, mins: int, queue: str,
                       project: str, res_req: str, n_cpus: int,
                       email: str = 'noemail', bsub: str = BSUB) -> str:
    """Build the (shell-quoted) bsub command line as a single string."""
    cmd = [bsub,
           '-q', str(queue),
           '-W', format_wallclock(mins),
           '-P', str(project),
           '-R', str(res_req),
           '-R', 'span[hosts=1]',
           '-n', str(n_cpus),
           '-J', str(job_name),
           '-oo', f'{job_name}.log',
           '-eo', f'{job_name}.err',
           '-u', str(email),
           str(script_file)]
    return ' '.join(shlex.quote(str(c)) for c in cmd)


def submit(acf_file: Path, mins: int = 720, queue: str = DEFAULT_QUEUE,
           project: str = None, res_req: str = DEFAULT_RES_REQ,
           adams_home: str = None, license_file: str = None,
           ld_library_path: str = None, email: str = 'noemail',
           dry_run: bool = False, args: list = None):
    job_name = acf_file.stem
    n_cpus = get_n_cpus(get_adm_from_acf(acf_file))

    script = build_job_script(acf_file, license_file=license_file,
                              adams_home=adams_home,
                              ld_library_path=ld_library_path)
    script_file = get_unique_file_name(Path(acf_file.with_suffix('.lsf').name))

    if dry_run:
        print(f'DRY-RUN: would write job script {script_file}:')
        print(script)
        cmd = build_bsub_command(script_file, job_name, mins=mins, queue=queue,
                                 project=project, res_req=res_req,
                                 n_cpus=n_cpus, email=email)
        print(f'DRY-RUN: would run: {cmd}')
        return None

    script_file.write_text(script)

    cmd = build_bsub_command(script_file, job_name, mins=mins, queue=queue,
                             project=project, res_req=res_req,
                             n_cpus=n_cpus, email=email)
    if args:
        cmd += ' ' + ' '.join(args)

    print(f'Running: {cmd}')
    return_code = subprocess.call(cmd, shell=True)
    if return_code != 0:
        print(f'bsub exited with status {return_code}', file=sys.stderr)
        sys.exit(1)


@contextmanager
def cwd_as(cwd: Path):
    _cwd = Path.cwd()
    os.chdir(cwd)

    try:
        yield
    finally:
        os.chdir(_cwd)


def excepthook(type, value, traceback):
    print(''.join(tb.format_exception(type, value, traceback)))
    sys.exit(1)


def main():
    sys.excepthook = excepthook

    parser = argparse.ArgumentParser(
        usage='%(prog)s <acf_file> [options]',
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter
        )
    parser.add_argument('acf_file', type=str, help='Path to the ACF file')
    parser.add_argument('--mins',
                        type=int,
                        default=60 * 12,
                        help='Wall-clock limit for the job, in minutes (default: 720)')
    parser.add_argument('--queue', type=str, default=DEFAULT_QUEUE,
                        help=f'LSF queue (default: {DEFAULT_QUEUE})')
    parser.add_argument('--project', type=str, default=os.environ.get('LSF_PROJECT'),
                        help='Charge code PRODUCT:RELEASE:GROUP:PURPOSE (required)')
    parser.add_argument('--res_req', type=str, default=DEFAULT_RES_REQ,
                        help='LSF resource requirement string')
    parser.add_argument('--adams_home', type=str, default=os.environ.get('ADAMS_HOME'),
                        help='Adams installation directory containing mdi (required)')
    parser.add_argument('--license', dest='license_file', type=str,
                        default=os.environ.get('MSC_LICENSE_FILE'),
                        help='MSC license file string, e.g. 1700@sjflex5 (required)')
    parser.add_argument('--ld_library_path', type=str,
                        default=os.environ.get('ADAMS_LD_LIBRARY_PATH'),
                        help='Optional LD_LIBRARY_PATH for the solver')
    parser.add_argument('--email', type=str, default='noemail',
                        help='bsub -u value (default: noemail)')
    parser.add_argument('--dry_run', action='store_true',
                        help='Print the bsub command line and job script instead of submitting')
    args, other_args = parser.parse_known_args()

    if not args.project:
        parser.error('--project is required (or set $LSF_PROJECT). '
                     'Format: PRODUCT:RELEASE:GROUP:PURPOSE')
    if not RE_PROJECT.fullmatch(args.project):
        parser.error(f'--project {args.project!r} does not match the required format '
                     'PRODUCT:RELEASE:GROUP:PURPOSE (e.g. MSC:2023.4:NNL:SIMULATION)')
    if not args.adams_home:
        parser.error('--adams_home is required (or set $ADAMS_HOME)')
    if not args.license_file:
        parser.error('--license is required (or set $MSC_LICENSE_FILE)')

    acf_file = Path(args.acf_file).absolute()
    mins = args.mins

    with cwd_as(acf_file.parent):
        submit(acf_file, mins=mins, queue=args.queue, project=args.project,
               res_req=args.res_req, adams_home=args.adams_home,
               license_file=args.license_file,
               ld_library_path=args.ld_library_path, email=args.email,
               dry_run=args.dry_run, args=other_args)


if __name__ == '__main__':

    main()
