#! /usr/bin/python3
'''Submit an ACF file to the cluster using LSF (Cadence sjlsf01 farm)

usage: lsf.py <acf_file> [options]

positional arguments:
  acf_file              Path to the ACF file

optional arguments:
  -h, --help            show this help message and exit
  --mins MINS           Wall-clock limit for the job, in minutes (default: 720)
  --queue QUEUE         LSF queue (default: lnx64)
  --project PROJECT     Farm project label, PRODUCT:RELEASE:GROUP:PURPOSE[:extra...]
                        (required; falls back to $LSF_PROJECT, then the
                        'project' key in ~/.aview_hpc)
  --res_req RES_REQ     LSF resource requirement string (default: pins to
                        RHEL 8.6+ or RHEL 9 hosts)
  --adams_home DIR      Adams installation directory containing `mdi`
                        (required; falls back to $ADAMS_HOME, then the
                        'adams_home' key in ~/.aview_hpc)
  --license LICENSE     MSC license file string, e.g. 1700@sjflex5
                        (required; falls back to $MSC_LICENSE_FILE, then the
                        'license' key in ~/.aview_hpc)
  --ld_library_path P   Optional LD_LIBRARY_PATH for the solver
                        (can also be supplied via $ADAMS_LD_LIBRARY_PATH)
  --email EMAIL         bsub -u value (default: noemail)
  --mem_mb MEM_MB       Memory request in MB -> rusage[mem=<MB>] inside the
                        single -R (aview_hpc's LSF backend sends this for the
                        generic `mem` submit kwarg)
  --dry_run             Print the bsub command line and the job script
                        instead of submitting

note:
  This will recognize the following:
    * The .adm file from the .acf file
    * The NTHREADS option in the .adm file

The submission goes through the site wrapper /grid/sfi/farm/bin/bsub, which
enforces the Cadence farm rules (mandatory -W and -P, etc.). On success bsub
prints "Job <id> is submitted to queue <queue>.", which is what the
aview_hpc client parses.

Why the ~/.aview_hpc fallback: aview_hpc runs this script through a
non-interactive SSH exec, which sources no login files, and the qual harness
never forwards --project/--adams_home/--license. Environment variables are
therefore usually absent, and the per-user config file is the only place a
farm-specific value can live. Precedence: CLI flag > environment > config.
'''

import argparse
import json
import os
import re
import shlex
import subprocess
import sys
import traceback as tb
from contextlib import contextmanager
from pathlib import Path

BSUB = '/grid/sfi/farm/bin/bsub'
DEFAULT_QUEUE = 'lnx64'
DEFAULT_RES_REQ = 'select[(OSMJR==8 && OSMNR>=6) || OSMJR>=9]'
# Site rule (sjlsf01 bsub wrapper): ^[A-Z]+:[^:]+:[A-Z]+:[^:]+ as a PREFIX, so
# optional trailing ``:field`` segments are allowed (Cadence IT: "-P
# <PRODUCT:release:GROUP:purpose[:optional-field]>").
RE_PROJECT = re.compile(r'[A-Z]+:[^:]+:[A-Z]+:[^:]+(?::[^:]+)*')
CONFIG_FILE = Path.home() / '.aview_hpc'


def load_config(config_file: Path = None) -> dict:
    """Read ~/.aview_hpc ON THE FARM HOST (where this script runs), not the
    client's copy. A missing or unreadable file is {}."""
    config_file = Path(config_file) if config_file else CONFIG_FILE
    try:
        with open(config_file) as f:
            config = json.load(f)
    except (OSError, ValueError):
        return {}
    if not isinstance(config, dict):
        return {}
    # Keep only non-empty string values: a mistyped value (number, list) must
    # surface as a clean "is required" parser error, not a TypeError later.
    return {k: v for k, v in config.items() if isinstance(v, str) and v.strip()}

RE_MODEL = re.compile(r'file/.*model[ \t]*=[ \t]*(.+)[ \t]*(?:,|$)', flags=re.I | re.MULTILINE)
RE_NTHREADS = re.compile(r'nthreads[ \t]*=[ \t]*(\d+)\b', flags=re.I)

JOB_SCRIPT_TEMPLATE = '''#!/bin/sh
# LSF job script generated by aview_hpc hpc_scripts/lsf.py
export LC_ALL=C
export MSC_LICENSE_FILE={license_file}
{ld_library_path}{adams_home}/mdi -c ru-s i {acf_file} exit
'''


def get_adm_from_acf(acf_file: Path):
    text = acf_file.read_text()

    try:
        line = next(l for l in text.splitlines())
    except StopIteration:
        raise ValueError(f'{acf_file} has no contents!')

    if line.strip() != '':
        file = line.strip()

    else:

        try:
            file = next(m for m in RE_MODEL.findall(text))
        except StopIteration:
            raise ValueError(f'No model name was found in {acf_file}')

    adm_file = Path(file)
    if not adm_file.suffix:
        adm_file = adm_file.with_suffix('.adm')

    return acf_file.parent / adm_file


def get_n_cpus(adm_file: Path):
    text = adm_file.read_text()
    try:
        n_threads = int(next(m for m in RE_NTHREADS.findall(text)))
    except StopIteration:
        # Set n_threads to 1 if not specified in .adm file
        n_threads = 1

    return n_threads


def get_unique_file_name(filename: Path):
    new_name = filename
    for i in range(999):

        if not new_name.exists():
            break

        new_name = filename.parent / f'{filename.stem}_{i}{filename.suffix}'

    return new_name


def format_wallclock(mins: int) -> str:
    """Format minutes as bsub's ``[hours:]minutes`` wall-clock limit."""
    mins = int(mins)
    if mins <= 0:
        raise ValueError('--mins must be a positive integer')
    return f'{mins // 60}:{mins % 60:02d}'


def build_job_script(acf_file: Path, license_file: str, adams_home: str,
                     ld_library_path: str = None) -> str:
    """Build the LSF job script contents."""
    return JOB_SCRIPT_TEMPLATE.format(
        license_file=license_file,
        ld_library_path=(f'export LD_LIBRARY_PATH={ld_library_path}\n'
                         if ld_library_path else ''),
        adams_home=str(adams_home).rstrip('/'),
        acf_file=Path(acf_file).name)


def build_bsub_command(script_file, job_name: str, mins: int, queue: str,
                       project: str, res_req: str, n_cpus: int,
                       email: str = 'noemail', mem_mb: int = None,
                       bsub: str = BSUB) -> str:
    """Build the (shell-quoted) bsub command line as a single string.

    The resource requirement and ``span[hosts=1]`` are joined into ONE ``-R``
    string: this LSF (10.1.0.15 site wrapper) rejects multiple ``-R`` options
    when a ``span``/``cu``/``affinity`` section is involved ("Multiple -R
    resource requirement strings are not supported on ..." — live-verified
    2026-10-01). A caller-supplied ``res_req`` that already contains a
    ``span[`` section is passed through as-is (no duplicate span appended);
    an empty/None ``res_req`` degrades to ``span[hosts=1]`` alone.

    ``mem_mb`` (integer megabytes, from aview_hpc's LSF backend
    ``translate_submit_kwargs`` -- the generic Slurm-syntax ``mem`` kwarg
    translated before it reaches this script) is rendered as
    ``rusage[mem=<MB>]`` and PREPENDED into the same single ``-R``
    (``rusage[mem=32768] select[...] span[hosts=1]``). LSF accepts select/
    rusage/span sections in one -R; a second ``-R`` would be rejected.
    A ``res_req`` that already carries its own ``rusage[`` section wins --
    an explicit site resource string is never silently overridden.

    Unlike ``sbatch``, bsub has no script-file argument: anything trailing the
    options is treated as the job COMMAND line. The job script is therefore
    fed via stdin redirection (live-verified accepted, 2026-10-01) — and
    nothing may be appended after the redirect.
    """
    res_req = str(res_req or '').strip()
    if mem_mb is not None:
        mem_mb = int(mem_mb)
        if mem_mb <= 0:
            raise ValueError('--mem_mb must be a positive integer')
        if 'rusage[' not in res_req:
            res_req = ' '.join(p for p in (f'rusage[mem={mem_mb}]', res_req) if p)
    combined_res_req = (res_req if 'span[' in res_req
                        else ' '.join(p for p in (res_req, 'span[hosts=1]') if p))
    cmd = [bsub,
           '-q', str(queue),
           '-W', format_wallclock(mins),
           '-P', str(project),
           '-R', combined_res_req,
           '-n', str(n_cpus),
           '-J', str(job_name),
           '-oo', f'{job_name}.log',
           '-eo', f'{job_name}.err',
           '-u', str(email)]
    return ' '.join(shlex.quote(str(c)) for c in cmd) + f' < {shlex.quote(str(script_file))}'


def submit(acf_file: Path, mins: int = 720, queue: str = DEFAULT_QUEUE,
           project: str = None, res_req: str = DEFAULT_RES_REQ,
           adams_home: str = None, license_file: str = None,
           ld_library_path: str = None, email: str = 'noemail',
           mem_mb: int = None, dry_run: bool = False, args: list = None):
    job_name = acf_file.stem
    n_cpus = get_n_cpus(get_adm_from_acf(acf_file))

    script = build_job_script(acf_file, license_file=license_file,
                              adams_home=adams_home,
                              ld_library_path=ld_library_path)

    # Everything (job script, bsub logs) is written next to the acf file.
    with cwd_as(acf_file.parent):
        script_file = get_unique_file_name(Path(acf_file.with_suffix('.lsf').name))

        if args:
            # bsub has no slot for extra arguments: words after the options
            # (and after the stdin redirect) are parsed as the job COMMAND
            # line, which would override the fed job script and exit 127.
            # Checked before the dry_run/real split so both paths behave
            # identically.
            raise SystemExit('Unsupported arguments forwarded to bsub (they '
                             'would become the job COMMAND line): '
                             + ' '.join(str(a) for a in args))

        cmd = build_bsub_command(script_file, job_name, mins=mins, queue=queue,
                                 project=project, res_req=res_req,
                                 n_cpus=n_cpus, email=email, mem_mb=mem_mb)

        if dry_run:
            print(f'DRY-RUN: would write job script {script_file}:')
            print(script)
            print(f'DRY-RUN: would run: {cmd}')
            return None

        script_file.write_text(script)

        print(f'Running: {cmd}')
        return_code = subprocess.call(cmd, shell=True)

    if return_code != 0:
        print(f'bsub exited with status {return_code}', file=sys.stderr)
        sys.exit(1)


@contextmanager
def cwd_as(cwd: Path):
    _cwd = Path.cwd()
    os.chdir(cwd)

    try:
        yield
    finally:
        os.chdir(_cwd)


def excepthook(type, value, traceback):
    print(''.join(tb.format_exception(type, value, traceback)))
    sys.exit(1)


def main():
    sys.excepthook = excepthook

    parser = argparse.ArgumentParser(
        usage='%(prog)s <acf_file> [options]',
        description=__doc__,
        # No prefix abbreviation: a client sending an untranslated option
        # (e.g. Slurm-era --mem) must hit the explicit "Unsupported arguments"
        # guard with the option NAMED, not die on an accidental prefix match
        # against --mem_mb/--mins with a confusing "invalid int value".
        allow_abbrev=False,
        formatter_class=argparse.RawTextHelpFormatter
        )
    parser.add_argument('acf_file', type=str, help='Path to the ACF file')
    parser.add_argument('--mins',
                        type=int,
                        default=60 * 12,
                        help='Wall-clock limit for the job, in minutes (default: 720)')
    parser.add_argument('--queue', type=str, default=DEFAULT_QUEUE,
                        help=f'LSF queue (default: {DEFAULT_QUEUE})')
    config = load_config()
    parser.add_argument('--project', type=str,
                        default=os.environ.get('LSF_PROJECT') or config.get('project'),
                        help='Farm project PRODUCT:RELEASE:GROUP:PURPOSE[:extra] (required)')
    parser.add_argument('--res_req', type=str, default=DEFAULT_RES_REQ,
                        help='LSF resource requirement string')
    parser.add_argument('--adams_home', type=str,
                        default=os.environ.get('ADAMS_HOME') or config.get('adams_home'),
                        help='Adams installation directory containing mdi (required)')
    parser.add_argument('--license', dest='license_file', type=str,
                        default=os.environ.get('MSC_LICENSE_FILE') or config.get('license'),
                        help='MSC license file string, e.g. 1700@sjflex5 (required)')
    parser.add_argument('--ld_library_path', type=str,
                        default=os.environ.get('ADAMS_LD_LIBRARY_PATH'),
                        help='Optional LD_LIBRARY_PATH for the solver')
    parser.add_argument('--email', type=str, default='noemail',
                        help='bsub -u value (default: noemail)')
    parser.add_argument('--mem_mb', type=int, default=None,
                        help='Memory request in MB, rendered as rusage[mem=<MB>] '
                             'inside the single -R (from aview_hpc translate_'
                             'submit_kwargs; the generic mem kwarg)')
    parser.add_argument('--dry_run', action='store_true',
                        help='Print the bsub command line and the job script instead of submitting')
    args, other_args = parser.parse_known_args()

    if not args.project:
        parser.error("--project is required (or set $LSF_PROJECT, or a 'project' key "
                     'in ~/.aview_hpc). Format: PRODUCT:RELEASE:GROUP:PURPOSE[:extra]')
    if not RE_PROJECT.fullmatch(args.project):
        parser.error(f'--project {args.project!r} does not match the required format '
                     'PRODUCT:RELEASE:GROUP:PURPOSE[:extra] (e.g. ADAMS:2023.4.1:AE:qual)')
    if not args.adams_home:
        parser.error("--adams_home is required (or set $ADAMS_HOME, or an 'adams_home' "
                     'key in ~/.aview_hpc)')
    if not args.license_file:
        parser.error("--license is required (or set $MSC_LICENSE_FILE, or a 'license' "
                     'key in ~/.aview_hpc)')

    acf_file = Path(args.acf_file).absolute()
    mins = args.mins

    submit(acf_file, mins=mins, queue=args.queue, project=args.project,
           res_req=args.res_req, adams_home=args.adams_home,
           license_file=args.license_file,
           ld_library_path=args.ld_library_path, email=args.email,
           mem_mb=args.mem_mb,
           dry_run=args.dry_run, args=other_args)


if __name__ == '__main__':

    main()
